/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class createWorkout extends javax.swing.JFrame {

    /**
     * Creates new form createWorkout
     */
    public createWorkout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        dm = new javax.swing.JTextField();
        descrip = new javax.swing.JTextField();
        wn = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        wid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cancel1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        cancel4 = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        dl = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 153));
        Header.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE USER WORKOUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 30));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(null);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel8.add(add);
        add.setBounds(10, 10, 100, 40);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(90, 50, 120, 60);

        dm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmActionPerformed(evt);
            }
        });
        jPanel2.add(dm);
        dm.setBounds(380, 350, 240, 30);

        descrip.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descrip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        jPanel2.add(descrip);
        descrip.setBounds(380, 270, 240, 30);

        wn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        wn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        wn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnActionPerformed(evt);
            }
        });
        jPanel2.add(wn);
        wn.setBounds(380, 230, 240, 30);

        cid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        jPanel2.add(cid);
        cid.setBounds(380, 190, 100, 30);

        wid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        wid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        wid.setEnabled(false);
        wid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widActionPerformed(evt);
            }
        });
        jPanel2.add(wid);
        wid.setBounds(380, 150, 100, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel10.setText("Duration minutes:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(230, 340, 160, 50);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel9.setText("Difficulty level:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(230, 300, 180, 50);

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel11.setText("Description:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(230, 260, 170, 50);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel8.setText("Workout Name:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(230, 220, 180, 50);

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel13.setText("Coach ID:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(230, 180, 170, 50);

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel6.setText("Workout ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(230, 140, 170, 50);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(null);

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel6.add(cancel);
        cancel.setBounds(10, 10, 100, 40);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(null);

        cancel1.setBackground(new java.awt.Color(0, 102, 102));
        cancel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel1.setText("CANCEL");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel7.add(cancel1);
        cancel1.setBounds(10, 10, 110, 40);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(510, 300, 130, 60);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(500, 50, 120, 60);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setLayout(null);

        cancel4.setBackground(new java.awt.Color(0, 102, 102));
        cancel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel4.setText("CANCEL");
        cancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel4ActionPerformed(evt);
            }
        });
        jPanel11.add(cancel4);
        cancel4.setBounds(10, 10, 110, 40);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(510, 300, 130, 60);

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel10.add(refresh);
        refresh.setBounds(10, 10, 100, 40);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(630, 50, 120, 60);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update);
        update.setBounds(10, 10, 100, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(220, 50, 120, 60);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(null);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear);
        clear.setBounds(10, 10, 100, 40);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(360, 50, 120, 60);

        dl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Intermediate", "Hard", "Advanced", "Expert", "Custom" }));
        dl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlActionPerformed(evt);
            }
        });
        jPanel2.add(dl);
        dl.setBounds(380, 310, 240, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    if (wn.getText().isEmpty() || descrip.getText().isEmpty() ||
        dl.getSelectedItem() == null || dm.getText().isEmpty() || cid.getText().isEmpty()) {

        JOptionPane.showMessageDialog(null, "All fields are required!");
        return;

    } else if (!dm.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Duration must be a number in minutes.");
        dm.setText("");
        return;
    }

    
    String workoutName = wn.getText().trim();
    String description = descrip.getText().trim();
    String difficultyLevel = dl.getSelectedItem().toString();
    int durationMinutes = Integer.parseInt(dm.getText().trim());
    int coachId = Integer.parseInt(cid.getText().trim());

    try {
        dbConnector dbc = new dbConnector();
        String sql = "INSERT INTO tbl_workout (coach_id, workout_name, description, difficulty_level, duration_minutes) "
                   + "VALUES (?, ?, ?, ?, ?)";

        PreparedStatement pst = dbc.connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pst.setInt(1, coachId);
        pst.setString(2, workoutName);
        pst.setString(3, description);
        pst.setString(4, difficultyLevel);
        pst.setInt(5, durationMinutes);

        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            ResultSet rs = pst.getGeneratedKeys();
            int workoutId = -1;
            if (rs.next()) {
                workoutId = rs.getInt(1);
            }

            
            Session sess = Session.getInstance();
            int userId = sess.getUserId();

            if (userId > 0) {
                String logAction = "Created Workout Record with ID No. " + workoutId;
                String logQuery = "INSERT INTO logs (user_id, action, date) VALUES (?, ?, NOW())";
                PreparedStatement logPst = dbc.connect.prepareStatement(logQuery);
                logPst.setInt(1, userId);
                logPst.setString(2, logAction);
                logPst.executeUpdate();
                logPst.close();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid session user ID. Logging skipped.");
            }

            JOptionPane.showMessageDialog(null, "Workout successfully added!");
            workoutForm wf = new workoutForm();
            wf.setVisible(true);
            this.dispose();
           
            wn.setText("");
            descrip.setText("");
            dl.setSelectedIndex(0);
            dm.setText("");
            cid.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Failed to add workout.");
        }

        pst.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        ex.printStackTrace();
    

    }


    }//GEN-LAST:event_addActionPerformed

    private void dmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmActionPerformed

    }//GEN-LAST:event_dmActionPerformed

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed

    }//GEN-LAST:event_descripActionPerformed

    private void wnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnActionPerformed

    }//GEN-LAST:event_wnActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void widActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widActionPerformed

    }//GEN-LAST:event_widActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        workoutForm wf = new workoutForm();
        wf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cancel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel4ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
   if (wid.getText().isEmpty() || wn.getText().isEmpty() || descrip.getText().isEmpty() ||
    dl.getSelectedItem() == null || dm.getText().isEmpty() || cid.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All fields are required!");
    return;

} else if (!dm.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "Duration must be a number in minutes.");
    dm.setText("");
    return;
}

int workoutId = Integer.parseInt(wid.getText().trim());
String workoutName = wn.getText().trim();
String description = descrip.getText().trim();
String difficultyLevel = dl.getSelectedItem().toString();
int durationMinutes = Integer.parseInt(dm.getText().trim());
int coachId = Integer.parseInt(cid.getText().trim());

try {
    dbConnector dbc = new dbConnector();

    String updateSQL = "UPDATE tbl_workout SET coach_id = ?, workout_name = ?, description = ?, difficulty_level = ?, duration_minutes = ? WHERE workout_id = ?";
    PreparedStatement pst = dbc.connect.prepareStatement(updateSQL);
    pst.setInt(1, coachId);
    pst.setString(2, workoutName);
    pst.setString(3, description);
    pst.setString(4, difficultyLevel);
    pst.setInt(5, durationMinutes);
    pst.setInt(6, workoutId);

    int rowsUpdated = pst.executeUpdate();

    if (rowsUpdated > 0) {
        // Log the update action
        Session sess = Session.getInstance();
        int userId = sess.getUserId();

        if (userId > 0) {
            String logAction = "Updated Workout Record with ID No. " + workoutId;
            String logQuery = "INSERT INTO logs (user_id, action, date) VALUES (?, ?, NOW())";
            PreparedStatement logPst = dbc.connect.prepareStatement(logQuery);
            logPst.setInt(1, userId);
            logPst.setString(2, logAction);
            logPst.executeUpdate();
            logPst.close();
        } else {
            JOptionPane.showMessageDialog(null, "Invalid session user ID. Logging skipped.");
        }

        JOptionPane.showMessageDialog(null, "Workout updated successfully!");
            workoutForm wf = new workoutForm();
            wf.setVisible(true);
            this.dispose();

       
        wn.setText("");
        descrip.setText("");
        dl.setSelectedIndex(0);
        dm.setText("");
        cid.setText("");
        wid.setText("");

    } else {
        JOptionPane.showMessageDialog(null, "Failed to update workout.");
    }

    pst.close();

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
    ex.printStackTrace();
}

     
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void dlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createWorkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    public javax.swing.JButton add;
    public javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel4;
    public javax.swing.JTextField cid;
    public javax.swing.JButton clear;
    public javax.swing.JTextField descrip;
    public javax.swing.JComboBox<String> dl;
    public javax.swing.JTextField dm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JButton refresh;
    public javax.swing.JButton update;
    public javax.swing.JTextField wid;
    public javax.swing.JTextField wn;
    // End of variables declaration//GEN-END:variables
}
