/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import com.mysql.jdbc.Statement;
import config.Session;
import config.dbConnector;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class CustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
    }
    
    private String action;
    public String destination =""; 
    File selectedFile;
    public String oldpath;
    public String path;
    
    public int FileExistenceChecker(String path){
        File file = new File(path);
        String fileName = file.getName();
        
        Path filePath = Paths.get("src/userimages", fileName);
        boolean fileExists = Files.exists(filePath);
        
        if (fileExists) {
            return 1;
        } else {
            return 0;
        }
    
    }
    public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }
    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
      public void imageUpdater(String existingFilePath, String newFilePath){
        File existingFile = new File(existingFilePath);
        if (existingFile.exists()) {
            String parentDirectory = existingFile.getParent();
            File newFile = new File(newFilePath);
            String newFileName = newFile.getName();
            File updatedFile = new File(parentDirectory, newFileName);
            existingFile.delete();
            try {
                Files.copy(newFile.toPath(), updatedFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                System.out.println("Image updated successfully.");
            } catch (IOException e) {
                System.out.println("Error occurred while updating the image: "+e);
            }
        } else {
            try{
                Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);
            }catch(IOException e){
                System.out.println("Error on update!");
            }
        }
    
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gn = new javax.swing.JComboBox<>();
        dj = new javax.swing.JTextField();
        coachid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cancel1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cancel2 = new javax.swing.JButton();
        cancel3 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        cid = new javax.swing.JTextField();
        uid = new javax.swing.JTextField();
        mid = new javax.swing.JTextField();
        stat = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        select = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(153, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel5.setText("Status:");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, 30));

        gn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        gn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnActionPerformed(evt);
            }
        });
        panel.add(gn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 240, 30));

        dj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djActionPerformed(evt);
            }
        });
        panel.add(dj, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 240, 30));

        coachid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coachid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coachid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        coachid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachidActionPerformed(evt);
            }
        });
        panel.add(coachid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel3.setText("Address:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 110, 50));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel7.setText("Gender:");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 50));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel9.setText("Date joined:");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 50));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel11.setText("Coach ID:");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, 50));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel8.setText("Membership ID:");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 50));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel13.setText("User ID:");
        panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 50));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 15)); // NOI18N
        jLabel6.setText("Customer ID:");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 50));

        address.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        panel.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 240, 30));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(null);

        cancel1.setBackground(new java.awt.Color(0, 102, 102));
        cancel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel1.setText("CANCEL");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        jPanel7.add(cancel1);
        cancel1.setBounds(10, 10, 110, 40);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(510, 300, 130, 60);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(null);

        cancel2.setBackground(new java.awt.Color(0, 102, 102));
        cancel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel2.setText("CANCEL");
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });
        jPanel9.add(cancel2);
        cancel2.setBounds(10, 10, 110, 40);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(510, 300, 130, 60);

        cancel3.setBackground(new java.awt.Color(255, 255, 255));
        cancel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel3.setText("CANCEL");
        cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel3ActionPerformed(evt);
            }
        });
        jPanel8.add(cancel3);
        cancel3.setBounds(10, 10, 100, 30);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 0);

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel6.add(cancel);
        cancel.setBounds(10, 10, 100, 30);

        panel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, 50));

        cid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cid.setEnabled(false);
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        panel.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 100, 30));

        uid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        panel.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 100, 30));

        mid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        panel.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, 30));

        stat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Separated" }));
        stat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statActionPerformed(evt);
            }
        });
        panel.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 240, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update);
        update.setBounds(10, 10, 100, 30);

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 120, 50));

        jPanel4.setLayout(null);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/781978-200-removebg-preview.png"))); // NOI18N
        jPanel4.add(image);
        image.setBounds(10, 16, 250, 250);

        panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 270, 280));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(null);

        select.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        select.setText("SELECT");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel5.add(select);
        select.setBounds(10, 10, 100, 30);

        panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 120, 50));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        add.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(10, 10, 100, 30);

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, 50));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 860, 450));

        Header.setBackground(new java.awt.Color(0, 153, 153));
        Header.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 860, 30));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnActionPerformed

    private void djActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djActionPerformed

    }//GEN-LAST:event_djActionPerformed

    private void coachidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachidActionPerformed

    }//GEN-LAST:event_coachidActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel2ActionPerformed

    private void cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel3ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      
    }//GEN-LAST:event_updateActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        CustomerDashboard customer = new CustomerDashboard();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
     
        JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    try {
                        selectedFile = fileChooser.getSelectedFile();
                        destination = "src/userimages/" + selectedFile.getName();
                        path  = selectedFile.getAbsolutePath();
                        
                        
                        if(FileExistenceChecker(path) == 1){
                          JOptionPane.showMessageDialog(null, "File Already Exist, Rename or Choose another!");
                            destination = "";
                            path="";
                        }else{
                            image.setIcon(ResizeImage(path, null, image));
                            select.setEnabled(false);           
                        }
                    } catch (Exception ex) {
                        System.out.println("File Error!");
                    }
                }

    }//GEN-LAST:event_selectActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
                 
    if ("Add".equals(action)) {
    dbConnector dbc = new dbConnector();
    int result = 0;

    try {
        if (uid == null || mid == null || coachid == null || dj == null || gn == null || stat == null || address == null || destination == null) {
            JOptionPane.showMessageDialog(null, "Some fields are missing or not initialized.");
            return;
        }

        String sql = "INSERT INTO tbl_customers (user_id, membership_id, coach_id, date_joined, gender, address, status, customer_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = dbc.connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, uid.getText());
        pst.setString(2, mid.getText());
        pst.setString(3, coachid.getText());
        pst.setString(4, dj.getText());
        pst.setString(5, gn.getSelectedItem().toString());
        pst.setString(6, address.getText());
        pst.setString(7, stat.getSelectedItem().toString());
        pst.setString(8, destination);
        pst.execute();

        ResultSet generatedKeys = pst.getGeneratedKeys();
        int generatedId = -1;
        if (generatedKeys.next()) {
            generatedId = generatedKeys.getInt(1);
        }

        Session sess = Session.getInstance();
        String logAction = "Created Student Record with ID No. " + generatedId;
        dbc.insertData("INSERT INTO logs (user_id, actions, date) VALUES('" + sess.getUserId() + "', '" + logAction + "', '" + LocalDateTime.now() + "')");

        if (selectedFile != null && destination != null) {
            Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);
        }

        result = 1;

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Insert Image Error: " + e.getMessage());
    }

    if (result == 1) {
        JOptionPane.showMessageDialog(null, "Successfully Saved!");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Saving Data Failed.");
    }

} else if ("Update".equals(action)) {
    // Your update logic here
}


    }//GEN-LAST:event_addActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
if ("add".equals(action)) {
    dbConnector dbc = new dbConnector();
    int result = 0;

    try {
        if (uid == null || mid == null || coachid == null || dj == null || gn == null || stat == null || address == null || destination == null) {
            JOptionPane.showMessageDialog(null, "Some fields are missing or not initialized.");
            return;
        }

        String sql = "INSERT INTO tbl_customers (user_id, membership_id, coach_id, date_joined, gender, address, status, customer_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = dbc.connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, uid.getText());
        pst.setString(2, mid.getText());
        pst.setString(3, coachid.getText());
        pst.setString(4, dj.getText());
        pst.setString(5, gn.getSelectedItem().toString());
        pst.setString(6, address.getText());
        pst.setString(7, stat.getSelectedItem().toString());
        pst.setString(8, destination);
        pst.execute();

        ResultSet generatedKeys = pst.getGeneratedKeys();
        int generatedId = -1;
        if (generatedKeys.next()) {
            generatedId = generatedKeys.getInt(1);
        }

        Session sess = Session.getInstance();
        String logAction = "Created Student Record with ID No. " + generatedId;
        dbc.insertData("INSERT INTO logs (user_id, actions, date) VALUES('" + sess.getUserId() + "', '" + logAction + "', '" + LocalDateTime.now() + "')");

        if (selectedFile != null && destination != null) {
            Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);
        }

        result = 1;
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Insert Image Error: " + e.getMessage());
    }

    if (result == 1) {
        JOptionPane.showMessageDialog(null, "Successfully Saved!");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Saving Data Failed.");
    }

} else if ("update".equals(action)) {
   
}    }//GEN-LAST:event_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    public javax.swing.JButton add;
    public javax.swing.JTextField address;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JButton cancel3;
    public javax.swing.JTextField cid;
    public javax.swing.JTextField coachid;
    public javax.swing.JTextField dj;
    public javax.swing.JComboBox<String> gn;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTextField mid;
    private javax.swing.JPanel panel;
    public javax.swing.JButton select;
    public javax.swing.JComboBox<String> stat;
    public javax.swing.JTextField uid;
    public javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
